# Generated by Django 4.2 on 2023-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History_Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textwe", models.CharField(max_length=200)),
                ("usuario_twe", models.CharField(max_length=30)),
                ("create_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
