# Generated by Django 4.2 on 2023-05-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history_tweet",
            old_name="textwe",
            new_name="usertextwe",
        ),
        migrations.RemoveField(
            model_name="history_tweet",
            name="usuario_twe",
        ),
    ]
