# Generated by Django 4.2 on 2023-05-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_textwe_history_tweet_usertextwe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_tweet',
            old_name='usertextwe',
            new_name='usertext',
        ),
    ]
