# Generated by Django 4.2 on 2023-05-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_usertextwe_history_tweet_usertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=200)),
                ('direccion_tweet', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
            ],
        ),
    ]
