# Generated by Django 4.2 on 2023-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_history_tweet_id_data_history_tweet_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_tweet',
            name='checked',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
